# Makefile for directory ./dom

TARGETS=\
	Counter.class\
	DOMAddLines.class\
	DOMGenerate.class\
	DOMParserWrapper.class\
	GetElementsByTagName.class\
	Writer.class

DIRS = traversal wrappers

TOP = ../..
include $(TOP)/src/Makefile.incl
