# Makefile for directory ./dom

TARGETS=\
	DOMAddLines.class\
	DOMCount.class\
	DOMFilter.class\
	DOMGenerate.class\
	DOMParserWrapper.class\
	DOMWriter.class

DIRS = traversal wrappers

TOP = ../..
include $(TOP)/src/Makefile.incl
