# Makefile for directory ./org/apache/xerces/jaxp

TARGETS = DocumentBuilderFactoryImpl.class\
        DocumentBuilderImpl.class\
        SAXParserFactoryImpl.class\
        SAXParserImpl.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
