# Makefile for directory ./org/apache/xerces/impl/validation/models

TARGETS=\
	DFAContentModel.class\
        MixedContentModel.class\
        SimpleContentModel.class

DIRS =


TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
