# Makefile for directory ./org/apache/xml/serialize

TARGETS=\
	OutputFormat.class\
	Method.class\
	LineSeparator.class\
	Serializer.class\
	DOMSerializer.class\
	BaseMarkupSerializer.class\
	XMLSerializer.class\
	HTMLSerializer.class\
	XHTMLSerializer.class\
	TextSerializer.class\
	ElementState.class\
	HTMLdtd.class\
	SerializerFactory.class\
	SerializerFactoryImpl.class \
	EncodingInfo.class \
	SieveEncodingInfo.class \
	Encodings.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
