# Makefile for directory ./javax/xml

TARGETS =\
        DocumentBuilder.class\
        DocumentBuilderFactory.class\
        FactoryConfigurationError.class\
        ParserConfigurationException.class\
        SAXParser.class\
        SAXParserFactory.class

DIRS =

TOP = ../../../..
include $(TOP)/src/Makefile.incl
