# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	PO_IF.class\
	Property.class\
	StringProperty.class

DIRS = 

TOP = ../../../../../../../../..
include $(TOP)/src/Makefile.incl
