# Makefile for directory ./sax

TARGETS=\
	DelayedInput.class\
	DocumentTracer.class\
	SAXCount.class\
	SAX2Count.class\
	SAXWriter.class\
	SAX2Writer.class

DIRS = helpers

TOP = ../..
include $(TOP)/src/Makefile.incl
