# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	xmlFactory.class\
	XMLFixed.class\
	XMLNumber.class\
	XMLRequired.class\
	XMLString.class\
	XMLStringIF.class

DIRS = 

TOP = ../../../../../../../../..
include $(TOP)/src/Makefile.incl
