TARGETS=\
	CMAny.class\
	CMBinOp.class\
	CMException.class\
	CMLeaf.class\
	CMNode.class\
	CMStateSet.class\
	CMUniOp.class\
	ContentLeafNameTypeVector.class\
	DFAContentModel.class\
	InsertableElementsInfo.class\
	MixedContentModel.class\
	SimpleContentModel.class\
	XMLContentModel.class\
	GrammarResolver.class \
	GrammarResolverImpl.class \
	Grammar.class \
	XMLValidator.class



DIRS =

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
