# Makefile for directory ./org/apache/xerces/parsers

TARGETS=\
	CachingParserPool.class\
        DOMParser.class\
        DTDParser.class\
        SAXParser.class\
        SchemaParser.class\
        XMLDocumentParser.class\
        XMLGrammarParser.class\
        XMLParser.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
