# Makefile for directory ./org/apache/xerces/parsers

TARGETS=\
	AbstractDOMParser.class\
	AbstractSAXParser.class\
	AbstractXMLDocumentParser.class\
	CachingParserPool.class\
        DOMParser.class\
        DTDParser.class\
        SAXParser.class\
        SchemaParser.class\
        XMLDocumentParser.class\
        XMLGrammarParser.class\
        XMLParser.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
