/*
 * The Apache Software License, Version 1.1
 *
 *
 * Copyright (c) 1999,2000 The Apache Software Foundation.  All rights 
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The end-user documentation included with the redistribution,
 *    if any, must include the following acknowledgment:  
 *       "This product includes software developed by the
 *        Apache Software Foundation (http://www.apache.org/)."
 *    Alternately, this acknowledgment may appear in the software itself,
 *    if and wherever such third-party acknowledgments normally appear.
 *
 * 4. The names "Xerces" and "Apache Software Foundation" must
 *    not be used to endorse or promote products derived from this
 *    software without prior written permission. For written 
 *    permission, please contact apache@apache.org.
 *
 * 5. Products derived from this software may not be called "Apache",
 *    nor may "Apache" appear in their name, without prior written
 *    permission of the Apache Software Foundation.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 1999, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

package org.apache.xerces.parsers;

import java.io.IOException;
import java.util.Locale;
import org.apache.xerces.framework.XMLString;
import org.apache.xerces.scanners.XMLDTDHandler;
import org.apache.xerces.utils.SymbolTable;
import org.apache.xerces.validators.GrammarPool;
import org.xml.sax.ContentHandler;
import org.xml.sax.DTDHandler;
import org.xml.sax.DocumentHandler;
import org.xml.sax.EntityResolver;
import org.xml.sax.ErrorHandler;
import org.xml.sax.InputSource;
import org.xml.sax.Parser;
import org.xml.sax.SAXException;
import org.xml.sax.SAXNotRecognizedException;
import org.xml.sax.SAXNotSupportedException;
import org.xml.sax.XMLReader;

/**
 * @author Stubs generated by DesignDoc on Mon Sep 11 11:10:57 PDT 2000
 * @version $Id$
 */
public class SAXParser
    extends XMLDocumentParser
    implements XMLDTDHandler, Parser, XMLReader {

    //
    // Constructors
    //

    /**
     * 
     */
    public SAXParser() {
    }

    /**
     * 
     * 
     * @param symbolTable 
     * @param grammarPool 
     */
    protected SAXParser(SymbolTable symbolTable, GrammarPool grammarPool) {
    }

    //
    // XMLDTDHandler methods
    //

    /**
     * startDTD
     */
    public void startDTD()
        throws SAXException {
    } // startDTD

    /**
     * comment
     * 
     * @param text 
     */
    public void comment(XMLString text)
        throws SAXException {
    } // comment

    /**
     * processingInstruction
     * 
     * @param target 
     * @param data 
     */
    public void processingInstruction(String target, XMLString data)
        throws SAXException {
    } // processingInstruction

    /**
     * startExternalSubset
     */
    public void startExternalSubset()
        throws SAXException {
    } // startExternalSubset

    /**
     * endExternalSubset
     */
    public void endExternalSubset()
        throws SAXException {
    } // endExternalSubset

    /**
     * elementDecl
     * 
     * @param name 
     * @param contentModel 
     */
    public void elementDecl(String name, XMLString contentModel)
        throws SAXException {
    } // elementDecl

    /**
     * startAttlist
     * 
     * @param elementName 
     */
    public void startAttlist(String elementName)
        throws SAXException {
    } // startAttlist

    /**
     * attributeDecl
     * 
     * @param elementName 
     * @param attributeName 
     * @param type 
     * @param enumeration 
     * @param defaultType 
     * @param defaultValue 
     */
    public void attributeDecl(String elementName, String attributeName, String type, String[] enumeration, String defaultType, XMLString defaultValue)
        throws SAXException {
    } // attributeDecl

    /**
     * endAttlist
     */
    public void endAttlist()
        throws SAXException {
    } // endAttlist

    /**
     * internalEntityDecl
     * 
     * @param name 
     * @param text 
     * @param isPE 
     */
    public void internalEntityDecl(String name, XMLString text, boolean isPE)
        throws SAXException {
    } // internalEntityDecl

    /**
     * externalEntityDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     * @param isPE 
     */
    public void externalEntityDecl(String name, String publicId, String systemId, boolean isPE)
        throws SAXException {
    } // externalEntityDecl

    /**
     * unparsedEntityDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     * @param notation 
     */
    public void unparsedEntityDecl(String name, String publicId, String systemId, String notation)
        throws SAXException {
    } // unparsedEntityDecl

    /**
     * notationDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     */
    public void notationDecl(String name, String publicId, String systemId)
        throws SAXException {
    } // notationDecl

    /**
     * startConditional
     * 
     * @param type 
     */
    public void startConditional(short type)
        throws SAXException {
    } // startConditional

    /**
     * endConditional
     */
    public void endConditional()
        throws SAXException {
    } // endConditional

    /**
     * endDTD
     */
    public void endDTD()
        throws SAXException {
    } // endDTD

    //
    // Parser methods
    //

    /**
     * parse
     * 
     * @param systemId 
     */
    public void parse(String systemId)
        throws IOException, SAXException {
    } // parse

    /**
     * parse
     * 
     * @param inputSource 
     */
    public void parse(InputSource inputSource)
        throws IOException, SAXException {
    } // parse

    /**
     * setLocale
     * 
     * @param locale 
     */
    public void setLocale(Locale locale)
        throws SAXException {
    } // setLocale

    /**
     * setEntityResolver
     * 
     * @param entityResolver 
     */
    public void setEntityResolver(EntityResolver entityResolver) {
    } // setEntityResolver

    /**
     * setDocumentHandler
     * 
     * @param documentHandler 
     */
    public void setDocumentHandler(DocumentHandler documentHandler) {
    } // setDocumentHandler

    /**
     * setDTDHandler
     * 
     * @param dtdHandler 
     */
    public void setDTDHandler(DTDHandler dtdHandler) {
    } // setDTDHandler

    /**
     * setErrorHandler
     * 
     * @param errorHandler 
     */
    public void setErrorHandler(ErrorHandler errorHandler) {
    } // setErrorHandler

    //
    // XMLReader methods
    //

    /**
     * parse
     * 
     * @param systemId 
     */
    public void parse(String systemId)
        throws IOException, SAXException {
    } // parse

    /**
     * parse
     * 
     * @param inputSource 
     */
    public void parse(InputSource inputSource)
        throws IOException, SAXException {
    } // parse

    /**
     * setEntityResolver
     * 
     * @param entityResolver 
     */
    public void setEntityResolver(EntityResolver entityResolver) {
    } // setEntityResolver

    /**
     * getEntityResolver
     * 
     * @return 
     */
    public EntityResolver getEntityResolver() {
        return null;
    } // getEntityResolver

    /**
     * setContentHandler
     * 
     * @param contentHandler 
     */
    public void setContentHandler(ContentHandler contentHandler) {
    } // setContentHandler

    /**
     * getContentHandler
     * 
     * @return 
     */
    public ContentHandler getContentHandler() {
        return null;
    } // getContentHandler

    /**
     * setDTDHandler
     * 
     * @param dtdHandler 
     */
    public void setDTDHandler(DTDHandler dtdHandler) {
    } // setDTDHandler

    /**
     * getDTDHandler
     * 
     * @return 
     */
    public DTDHandler getDTDHandler() {
        return null;
    } // getDTDHandler

    /**
     * setErrorHandler
     * 
     * @param errorHandler 
     */
    public void setErrorHandler(ErrorHandler errorHandler) {
    } // setErrorHandler

    /**
     * getErrorHandler
     * 
     * @return 
     */
    public ErrorHandler getErrorHandler() {
        return null;
    } // getErrorHandler

    /**
     * setFeature
     * 
     * @param featureId 
     * @param state 
     */
    public void setFeature(String featureId, int state)
        throws SAXNotRecognizedException, SAXNotSupportedException {
    } // setFeature

    /**
     * getFeature
     * 
     * @param featureId 
     * 
     * @return 
     */
    public int getFeature(String featureId)
        throws SAXNotRecognizedException, SAXNotSupportedException {
        return -1;
    } // getFeature

    /**
     * setProperty
     * 
     * @param propertyId 
     * @param value 
     */
    public void setProperty(String propertyId, Object value)
        throws SAXNotRecognizedException, SAXNotSupportedException {
    } // setProperty

    /**
     * getProperty
     * 
     * @param propertyId 
     * 
     * @return 
     */
    public Object getProperty(String propertyId)
        throws SAXNotRecognizedException, SAXNotSupportedException {
        return null;
    } // getProperty

} // class SAXParser
