/*
 * The Apache Software License, Version 1.1
 *
 *
 * Copyright (c) 1999,2000 The Apache Software Foundation.  All rights 
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The end-user documentation included with the redistribution,
 *    if any, must include the following acknowledgment:  
 *       "This product includes software developed by the
 *        Apache Software Foundation (http://www.apache.org/)."
 *    Alternately, this acknowledgment may appear in the software itself,
 *    if and wherever such third-party acknowledgments normally appear.
 *
 * 4. The names "Xerces" and "Apache Software Foundation" must
 *    not be used to endorse or promote products derived from this
 *    software without prior written permission. For written 
 *    permission, please contact apache@apache.org.
 *
 * 5. Products derived from this software may not be called "Apache",
 *    nor may "Apache" appear in their name, without prior written
 *    permission of the Apache Software Foundation.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 1999, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

package org.apache.xerces.impl.validation;

import java.util.Hashtable;

/**
 * A grammar pool.
 *
 * @author Stubs generated by DesignDoc on Mon Sep 11 11:10:57 PDT 2000
 * @author Jeffrey Rodriguez, IBM
 * @author Andy Clark, IBM
 *
 * @version $Id$
 */
public class GrammarPool {

    //
    // Data
    //

    /** Grammars. */
    protected Hashtable fGrammars = new Hashtable();

    //
    // Constructors
    //

    /** Default constructor. */
    public GrammarPool() {
    } // <init>()

    //
    // Public methods
    //

    /**
     * Puts the specified grammar into the grammar pool.
     * 
     * @param key Key to associate with grammar.
     * @param grammar Grammar object.
     */
    public void putGrammar(String key, Grammar grammar) {
        fGrammars.put(key, grammar);
    } // putGrammar(String,Grammar)

    /**
     * Returns the grammar associated to the specified key.
     * 
     * @param key The key of the grammar.
     */
    public Grammar getGrammar(String key) {
        return (Grammar)fGrammars.get(key);
    } // getGrammar(String):Grammar

    /**
     * Removes the grammar associated to the specified key from the
     * grammar pool and returns the removed grammar.
     * 
     * @param key The key of the grammar.
     */
    public Grammar removeGrammar(String key) {
        if (fGrammars.contains(key)) {
            return (Grammar)fGrammars.remove(key);
        }
        return null;
    } // removeGrammar(String):Grammar

    /**
     * Returns true if the grammar pool contains a grammar associated
     * to the specified key.
     *
     * @param key The key of the grammar.
     */
    public boolean containsGrammar(String key) {
        return fGrammars.containsKey(key);
    } // containsGrammar(String):boolean

} // class GrammarPool
