# Makefile for directory ./org/apache/xerces/impl/validation

TARGETS=\
	ContentModelValidator.class\
        DatatypeValidator.class\
        DatatypeValidatorFactory.class\
        Grammar.class\
        GrammarPool.class\
        InvalidDatatypeFacetException.class\
        InvalidDatatypeValueException.class\
        XMLAttributeDecl.class\
        XMLElementDecl.class\
        XMLEntityDecl.class\
        XMLNotationDecl.class\
        XMLSimpleType.class

DIRS = datatypes grammars models validators


TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
