TARGETS=\
	BMPattern.class \
	Match.class \
	Op.class \
	ParseException.class \
	ParserForXMLSchema.class \
	REUtil.class \
	RangeToken.class \
	RegexParser.class \
	RegularExpression.class \
	Token.class 


DIRS =

TOP = ../../../../../../../..
include $(TOP)/src/Makefile.incl
