# Makefile for directory ./org/apache/xerces/validators/schema/identity

TARGETS=\
	Field.class\
	FieldActivator.class\
	IdentityConstraint.class\
	IDValue.class\
	Key.class\
	KeyRef.class\
	Selector.class\
	Unique.class\
	ValueStore.class\
	XPath.class\
	XPathException.class\
	XPathMatcher.class

DIRS = 

TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
