# Makefile for directory ./org/w3c/dom/traversal

TARGETS=\
     DocumentTraversal.class\
     NodeFilter.class\
     NodeIterator.class\
     TreeWalker.class

DIRS = 

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
