# Makefile for directory ./org/apache/xerces/msg

TARGETS=\
	DatatypeMessages.class\
	ExceptionMessages.class \
	SchemaMessages.class\
	XMLMessages.class\
	ImplementationMessages.class

DIRS =


TOP = ../../../../..
include $(TOP)/src/Makefile.incl
