# Makefile for directory ./ui

TARGETS=\
	DefaultImages.class\
	DOMParserSaveEncoding.class\
	DOMTree.class\
	DOMTreeFull.class\
	TreeView.class\
	TreeViewer.class

DIRS = 

TOP = ../..
include $(TOP)/src/Makefile.incl
