# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	ISO8601.class\
	ISO8601Pattern.class\
	ISODate.class\
	ISODateTime.class\
	ISOPeriod.class\
	ISOTime.class

DIRS = 

TOP = ../../../../../../../../../..
include $(TOP)/src/Makefile.incl
