# Makefile for directory ./org/apache/xerces/dom

TARGETS=\
	AttrImpl.class\
	AttributeMap.class\
	AttrNSImpl.class\
	CDATASectionImpl.class\
	CharacterDataImpl.class\
	ChildNode.class\
	ChildAndParentNode.class\
	CommentImpl.class\
	DeepNodeListImpl.class\
	DeferredAttrImpl.class\
	DeferredAttrNSImpl.class\
	DeferredCDATASectionImpl.class\
	DeferredCommentImpl.class\
	DeferredDocumentImpl.class\
	DeferredDocumentTypeImpl.class\
	DeferredElementDefinitionImpl.class\
	DeferredElementImpl.class\
	DeferredElementNSImpl.class\
	DeferredEntityImpl.class\
	DeferredEntityReferenceImpl.class\
	DeferredNode.class\
	DeferredNotationImpl.class\
	DeferredProcessingInstructionImpl.class\
	DeferredTextImpl.class\
	DocumentFragmentImpl.class\
	DocumentImpl.class\
	DocumentTypeImpl.class\
	DOMExceptionImpl.class\
	DOMImplementationImpl.class\
	ElementDefinitionImpl.class\
	ElementImpl.class\
	ElementNSImpl.class\
	EntityImpl.class\
	EntityReferenceImpl.class\
	LCount.class\
	NamedNodeMapImpl.class\
	NodeImpl.class\
	NodeIteratorImpl.class\
	NotationImpl.class\
	ParentNode.class\
	ProcessingInstructionImpl.class\
	RangeExceptionImpl.class\
	RangeImpl.class\
	TextImpl.class\
	TreeWalkerImpl.class

DIRS = events

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
