# Makefile for directory ./org/w3c/dom/events

TARGETS=\
     DocumentEvent.class\
     Event.class\
     EventException.class\
     EventListener.class\
     EventTarget.class\
     MutationEvent.class

DIRS= 

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
