# Makefile for directory ./org/apache/xerces/util

TARGETS=\
	EncodingMap.class\
        MessageFormatter.class\
        SymbolTable.class\
        XMLChar.class\
        XMLStringBuffer.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
