# Makefile for directory ./org/apache/xerces/impl/validation/identity

TARGETS=\
	Field.class\
	FieldActivator.class\
	IdentityConstraint.class\
	Key.class\
	KeyRef.class\
	Selector.class\
	Unique.class\
	ValueStore.class

DIRS = 

TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
