# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	AbstractDatatypeValidator.class\
	Base64.class\
	BinaryDatatypeValidator.class\
	BooleanDatatypeValidator.class\
	DatatypeMessageProvider.class\
	DatatypeValidatorFactoryImpl.class\
	DecimalDatatypeValidator.class\
	DoubleDatatypeValidator.class\
	ENTITYDatatypeValidator.class \
	FloatDatatypeValidator.class\
	HexBin.class\
	IDDatatypeValidator.class \
	IDREFDatatypeValidator.class \
	NOTATIONDatatypeValidator.class \
	QNameDatatypeValidator.class\
	StringDatatypeValidator.class\
	URIReferenceDatatypeValidator.class \
	RecurringDurationDatatypeValidator.class\
	TimeDurationDatatypeValidator.class\
	DatatypeValidatorFactoryImpl.class

DIRS = regex 

TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
