# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	AbstractDatatypeValidator.class\
        DatatypeValidatorFactoryImpl.class\
        StringDatatypeValidator.class

DIRS =


TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
