# Makefile for directory ./org/apache/xerces/xni

TARGETS=\
	NamespaceContext.class\
	QName.class\
        XMLAttributes.class\
	XMLDocumentFragmentHandler.class\
        XMLDocumentHandler.class\
        XMLDTDContentModelHandler.class\
        XMLDTDHandler.class\
        XMLString.class

DIRS = parser

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
