# Makefile for directory ./org/apache/xerces/xni

TARGETS=\
	QName.class\
        XMLAttributes.class\
        XMLComponent.class\
        XMLComponentManager.class\
        XMLDTDContentModelHandler.class\
        XMLDTDContentModelSource.class\
        XMLDTDHandler.class\
        XMLDTDSource.class\
        XMLDocumentHandler.class\
        XMLDocumentSource.class\
        XMLString.class

DIRS = parser

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
