# Makefile for directory ./org/w3c/dom

TARGETS=\
	Attr.class\
	CDATASection.class\
	CharacterData.class\
	Comment.class\
	Document.class\
	DocumentFragment.class\
	DocumentType.class\
	DOMException.class\
	DOMImplementation.class\
	Element.class\
	Entity.class\
	EntityReference.class\
	NamedNodeMap.class\
	Node.class\
	NodeList.class\
	Notation.class\
	ProcessingInstruction.class\
	Text.class

DIRS = events html traversal range

TOP = ../../../..
include $(TOP)/src/Makefile.incl
