# Makefile for directory ./org/apache/xerces/utils

TARGETS=\
	CharDataChunk.class\
	ChunkyByteArray.class\
	ChunkyCharArray.class\
	NamespacesScope.class\
	StringHasher.class\
	StringPool.class\
	SymbolCache.class\
	UTF8DataChunk.class\
	ImplementationMessages.class\
	XMLCharacterProperties.class\
	XMLMessageProvider.class\
	XMLMessages.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
