# Makefile for directory ./org/apache/xerces/utils

TARGETS=\
       Base64.class\
	CharDataChunk.class\
	ChunkyByteArray.class\
	ChunkyCharArray.class\
	Hash2intTable.class\
	HexBin.class\
	ImplementationMessages.class\
	IntStack.class\
	ISO8601Format.class\
	NamespacesScope.class\
	QName.class\
	StringHasher.class\
	StringPool.class\
	SymbolCache.class\
	URI.class\
	UTF8DataChunk.class\
	XMLCharacterProperties.class\
	XMLMessageProvider.class\
	XMLMessages.class

DIRS = regex

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
