# Makefile for directory ./org/apache/wml

TARGETS=\
      WMLAElement.class\
      WMLAccessElement.class\
      WMLAnchorElement.class\
      WMLBElement.class\
      WMLBigElement.class\
      WMLBrElement.class\
      WMLCardElement.class\
      WMLDOMImplementation.class\
      WMLDoElement.class\
      WMLDocument.class\
      WMLElement.class\
      WMLEmElement.class\
      WMLFieldsetElement.class\
      WMLGoElement.class\
      WMLHeadElement.class\
      WMLIElement.class\
      WMLImgElement.class\
      WMLInputElement.class\
      WMLMetaElement.class\
      WMLNoopElement.class\
      WMLOneventElement.class\
      WMLOptgroupElement.class\
      WMLOptionElement.class\
      WMLPElement.class\
      WMLPostfieldElement.class\
      WMLPrevElement.class\
      WMLRefreshElement.class\
      WMLSelectElement.class\
      WMLSetvarElement.class\
      WMLSmallElement.class\
      WMLStrongElement.class\
      WMLTableElement.class\
      WMLTdElement.class\
      WMLTemplateElement.class\
      WMLTimerElement.class\
      WMLTrElement.class\
      WMLUElement.class\
      WMLWmlElement.class

DIRS = dom

TOP = ../../../..
include $(TOP)/src/Makefile.incl

