# Makefile for directory ./org/apache/xerces/xni/parser

TARGETS=\
        XMLComponent.class\
        XMLComponentManager.class\
        XMLParserConfiguration.class

DIRS =

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
