# Makefile for directory ./org/apache/xerces/impl/validation/validators

TARGETS=\
        XMLDTDValidator.class\
        XMLSchemaValidator.class

DIRS =


TOP = ../../../../../../..
include $(TOP)/src/Makefile.incl
