# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	AbstractProperty.class\
	Helpers.class\
	PartialOrder.class

DIRS = 

TOP = ../../../../../../../../..
include $(TOP)/src/Makefile.incl
