# Makefile for directory ./org/apache/xerces/impl

TARGETS=\
        Constants.class\
        Version.class\
        XMLDocumentScanner.class\
        XMLDTDScanner.class\
        XMLEntityHandler.class\
        XMLEntityManager.class\
        XMLEntityScanner.class\
        XMLErrorReporter.class\
	XMLInputSource.class\
        XMLScanner.class\
        XMLValidator.class

DIRS = msg validation io

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
