# Makefile for directory ./org/apache/xerces/impl

TARGETS=\
        Version.class\
        XMLDTDScanner.class\
        XMLDocumentScanner.class\
        XMLEntityManager.class\
        XMLEntityScanner.class\
        XMLErrorReporter.class\
        XMLValidator.class

DIRS = msg validation

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
