# Makefile for directory ./org/xml/sax/helpers

TARGETS=\
	AttributesImpl.class\
	AttributeListImpl.class\
	DefaultHandler.class\
	LocatorImpl.class\
	NamespaceSupport.class\
	ParserAdapter.class\
	ParserFactory.class\
	XMLFilterImpl.class\
	XMLReaderAdapter.class\
	XMLReaderFactory.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
