# Makefile for directory ./org/apache/xerces/validators/schema

TARGETS=\
	DatatypeContentModel.class\
	SchemaImporter.class\
	SchemaParser.class\
	Schema.class\
	SchemaMessageProvider.class\
	SchemaSymbols.class \
	TraverseSchema.class \
	XUtil.class

DIRS = 

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
