# Makefile for directory ./org/apache/xerces/validators/schema

TARGETS=\
	SubstitutionGroupComparator.class\
	SchemaGrammar.class\
	SchemaMessageProvider.class\
	SchemaSymbols.class \
	TraverseSchema.class \
	XUtil.class

DIRS = 

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
