# Makefile for directory ./org/xml/sax

TARGETS=\
	Attributes.class\
	AttributeList.class\
	ContentHandler.class\
	DocumentHandler.class\
	DTDHandler.class\
	EntityResolver.class\
	ErrorHandler.class\
	HandlerBase.class\
	InputSource.class\
	Locator.class\
	Parser.class\
	SAXException.class\
	SAXNotRecognizedException.class\
	SAXNotSupportedException.class\
	SAXParseException.class\
	XMLFilter.class\
	XMLReader.class

DIRS = helpers ext

TOP = ../../../..
include $(TOP)/src/Makefile.incl
