# Makefile for directory ./org/apache/xerces/impl/validation/datatypes

TARGETS=\
	BasicStringProperty.class\
	NamedMatch.class\
	uri.class

DIRS = datime Number

TOP = ../../../../../../../../..
include $(TOP)/src/Makefile.incl
