# Makefile for directory ./org/apache/xerces/validators/dtd

TARGETS=\
	CMBinOp.class\
	CMException.class\
	CMLeaf.class\
	CMNode.class\
	CMStateSet.class\
	CMUniOp.class\
	DFAContentModel.class\
	DTDValidator.class\
	ElementDeclPool.class\
	EntityPool.class\
	InsertableElementsInfo.class\
	MixedContentModel.class\
	SimpleContentModel.class\
	XMLContentModel.class

DIRS = 

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
