# Makefile for directory ./org/apache/xerces/readers

TARGETS=\
	AbstractCharReader.class\
	CharReader.class\
	DefaultReaderFactory.class\
	EBCDICRecognizer.class\
	MIME2Java.class\
	StreamingCharReader.class\
	StringReader.class\
	UCSReader.class\
	UCSRecognizer.class\
	UTF8CharReader.class\
	UTF8Reader.class\
	UTF8Recognizer.class\
	XCatalog.class\
	XMLCatalogHandler.class\
	XMLDeclRecognizer.class\
	XMLEntityHandler.class\
	XMLEntityReader.class\
	XMLEntityReaderFactory.class

DIRS = 

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
