# Makefile for directory ./org/apache/xerces/framework

TARGETS=\
	Version.class\
	XMLAttrList.class\
	XMLContentSpec.class\
	XMLDocumentHandler.class\
	XMLDocumentScanner.class\
	XMLDTDScanner.class\
	XMLErrorReporter.class\
	XMLParser.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
