# Makefile for directory ./org/apache/xerces/framework

TARGETS=\
	Version.class\
	XMLAttrList.class\
	XMLContentSpecNode.class\
	XMLDocumentScanner.class\
	XMLDTDScanner.class\
	XMLErrorReporter.class\
	XMLParser.class\
	XMLValidator.class

DIRS =

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
