# Makefile for directory ./org/apache/wml/dom

TARGETS=\
      WMLAElementImpl.class\
      WMLAccessElementImpl.class\
      WMLAnchorElementImpl.class\
      WMLBElementImpl.class\
      WMLBigElementImpl.class\
      WMLBrElementImpl.class\
      WMLCardElementImpl.class\
      WMLDOMImplementationImpl.class\
      WMLDoElementImpl.class\
      WMLDocumentImpl.class\
      WMLElementImpl.class\
      WMLEmElementImpl.class\
      WMLFieldsetElementImpl.class\
      WMLGoElementImpl.class\
      WMLHeadElementImpl.class\
      WMLIElementImpl.class\
      WMLImgElementImpl.class\
      WMLInputElementImpl.class\
      WMLMetaElementImpl.class\
      WMLNoopElementImpl.class\
      WMLOneventElementImpl.class\
      WMLOptgroupElementImpl.class\
      WMLOptionElementImpl.class\
      WMLPElementImpl.class\
      WMLPostfieldElementImpl.class\
      WMLPrevElementImpl.class\
      WMLRefreshElementImpl.class\
      WMLSelectElementImpl.class\
      WMLSetvarElementImpl.class\
      WMLSmallElementImpl.class\
      WMLStrongElementImpl.class\
      WMLTableElementImpl.class\
      WMLTdElementImpl.class\
      WMLTemplateElementImpl.class\
      WMLTimerElementImpl.class\
      WMLTrElementImpl.class\
      WMLUElementImpl.class\
      WMLWmlElementImpl.class

DIRS = 

TOP = ../../../../..
include $(TOP)/src/Makefile.incl
