TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
# Makefile for directory ./org/apache/xerces/utils/regex
#
# This makefile depends on the following environment variables
# already being defined:
#
#   JAVAC   Java compiler (with options)
#   RM      Host delete file command (with options)
#
# In addition, the CLASSPATH environment variable must
# include the absolute path of the base source directory.

TARGETS=\
	BMPattern.class \
	Match.class \
	Op.class \
	ParseException.class \
	ParserForXMLSchema.class \
	REUtil.class \
	RangeToken.class \
	RegexParser.class \
	RegularExpression.class \
	Token.class 


DIRS =

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
