/*
 * The Apache Software License, Version 1.1
 *
 *
 * Copyright (c) 1999,2000 The Apache Software Foundation.  All rights 
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The end-user documentation included with the redistribution,
 *    if any, must include the following acknowledgment:  
 *       "This product includes software developed by the
 *        Apache Software Foundation (http://www.apache.org/)."
 *    Alternately, this acknowledgment may appear in the software itself,
 *    if and wherever such third-party acknowledgments normally appear.
 *
 * 4. The names "Xerces" and "Apache Software Foundation" must
 *    not be used to endorse or promote products derived from this
 *    software without prior written permission. For written 
 *    permission, please contact apache@apache.org.
 *
 * 5. Products derived from this software may not be called "Apache",
 *    nor may "Apache" appear in their name, without prior written
 *    permission of the Apache Software Foundation.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of the Apache Software Foundation and was
 * originally based on software copyright (c) 1999, International
 * Business Machines, Inc., http://www.apache.org.  For more
 * information on the Apache Software Foundation, please see
 * <http://www.apache.org/>.
 */

package org.apache.xerces.impl.validation.grammars;

import org.apache.xerces.xni.XMLString;
import org.apache.xerces.xni.XMLDTDContentModelHandler;
import org.apache.xerces.xni.XMLDTDHandler;
import org.apache.xerces.impl.validation.Grammar;
import org.apache.xerces.impl.validation.XMLElementDecl;
import org.apache.xerces.impl.validation.XMLAttributeDecl;
import org.apache.xerces.impl.validation.XMLNotationDecl;
import org.apache.xerces.impl.validation.XMLEntityDecl;
import org.apache.xerces.impl.validation.XMLSimpleType;
import org.apache.xerces.xni.QName;
import org.xml.sax.SAXException;

/**
 * @author Stubs generated by DesignDoc on Mon Sep 11 11:10:57 PDT 2000
 * @version $Id$
 */
public class DTDGrammar
    extends Grammar
    implements XMLDTDHandler, XMLDTDContentModelHandler {

    //
    // Data
    //

    /** Current ElementIndex */
    private int              fCurrentElementIndex;

    /** Element declaration. */
    private XMLElementDecl    fElementDecl        = new XMLElementDecl();

    /** Current AttributeIndex */
    private int               fCurrentAttributeIndex;

    /** Attribute declaration. */
    private XMLAttributeDecl  fAttributeDecl      = new XMLAttributeDecl();

    /** QName holder           */
    private QName             fQName              = new QName();

    /** XMLEntityDecl. */
    private XMLEntityDecl     fEntityDecl         = new XMLEntityDecl();

    /** internal XMLEntityDecl. */
    private XMLEntityDecl     fInternalEntityDecl = new XMLEntityDecl();

    /** external XMLEntityDecl */
    private XMLEntityDecl     fExternalEntityDecl = new XMLEntityDecl();

    /** Simple Type. */
    private XMLSimpleType     fSimpleType         = new XMLSimpleType();


    /** setDTDHandler */
    protected XMLDTDHandler setDTDHandler;

    /** setDTDContentModelHandler */
    protected XMLDTDContentModelHandler setDTDContentModelHandler;


     // debugging

    /** Debug DTDGrammar. */
    private static final boolean DEBUG_SCANNER_STATE = false;



    //
    // Constructors
    //

    /**
     * 
     */
    public DTDGrammar() {
           }

    /**
     * 
     * 
     * @param targetNamespace 
     */
    public DTDGrammar(String targetNamespace) {
    }

    //
    // XMLEntityHandler methods
    //

    /**
     * startEntity
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     * @param encoding
     */
    public void startEntity(String name, String publicId, String systemId, String encoding)
        throws SAXException {
        this.fEntityDecl.setValues( name, publicId, systemId, null, null, false );//fill internal fEntityDecl struct
    }

    /**
     * endEntity
     * 
     * @param name 
     */
    public void endEntity(String name)
        throws SAXException {
    }

    //
    // XMLDTDHandler methods
    //

    /**
     * startDTD
     */
    public void startDTD()
        throws SAXException {
        if( setDTDHandler != null){
            setDTDHandler.startDTD();//callback
        }
    } // startDTD

    /**
     * comment
     * 
     * @param text 
     */
    public void comment(XMLString text)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.comment( text );
        }
    } // comment

    /**
     * processingInstruction
     * 
     * @param target 
     * @param data 
     */
    public void processingInstruction(String target, XMLString data)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.processingInstruction( target, data );
        }
    } // processingInstruction

    /**
     * startExternalSubset
     */
    public void startExternalSubset()
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.startExternalSubset();
        }
       
    } // startExternalSubset

    /**
     * endExternalSubset
     */
    public void endExternalSubset()
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.endExternalSubset();
        }
    } // endExternalSubset

    /**
     * elementDecl
     * 
     * @param name 
     * @param contentModel 
     */
    public void elementDecl(String name, XMLString contentModel)
        throws SAXException {
        fCurrentElementIndex = createElementDecl();//create element decl
        //set element decl
        fElementDecl.clear();
        fElementDecl.name.setValues( null, null, name, null );

        setElementDecl(fCurrentElementIndex, fElementDecl );//set internal structure
        if( setDTDHandler != null ){
            setDTDHandler.elementDecl( name, contentModel );
        }
    } // elementDecl

    /**
     * startAttlist
     * 
     * @param elementName 
     */
    public void startAttlist(String elementName)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.startAttlist( elementName );
        }
    } // startAttlist

    /**
     * attributeDecl
     * 
     * @param elementName 
     * @param attributeName 
     * @param type 
     * @param enumeration 
     * @param defaultType 
     * @param defaultValue 
     */
    public void attributeDecl(String elementName, String attributeName, String type, String[] enumeration, String defaultType, XMLString defaultValue)
        throws SAXException {

        fCurrentAttributeIndex = createAttributeDecl();// Create current Attribute Decl
        fAttributeDecl.clear();
        fAttributeDecl.name.setValues(null,null,elementName,null);

        fSimpleType.clear();
        if( defaultType.equals( "DEFAULT" ) ){
            fSimpleType.defaultType = fSimpleType.DEFAULT_TYPE_DEFAULT;
        } else if( defaultType.equals( "FIXED") ) {
            fSimpleType.defaultType = fSimpleType.DEFAULT_TYPE_FIXED;
        } else if( defaultType.equals( "IMPLIED") ) {
           fSimpleType.defaultType = fSimpleType.DEFAULT_TYPE_IMPLIED;
        } else if( defaultType.equals( "REQUIRED") ) {
           fSimpleType.defaultType = fSimpleType.DEFAULT_TYPE_REQUIRED;
        }
        fSimpleType.defaultValue      = defaultValue.toString();

        fSimpleType.enumeration       = enumeration;
        /*   todo when we implement datatypes
        fSimpleType.datatypeValidator = DatatypeValidatorFactoryImpl.getDatatypeRegistry().getDatatypeValidator(type);
        */

        fAttributeDecl.simpleType = fSimpleType;
        setAttributeDecl( fCurrentElementIndex, fCurrentAttributeIndex,
                                                               fAttributeDecl );
        if( setDTDHandler != null ){
            setDTDHandler.attributeDecl( elementName, attributeName, type,
                                       enumeration, defaultType, defaultValue );
        }

    } // attributeDecl

    /**
     * endAttlist
     */
    public void endAttlist()
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.endAttlist();
        }
    } // endAttlist

    /**
     * internalEntityDecl
     * 
     * @param name 
     * @param text 
     * @param isPE 
     */
    public void internalEntityDecl(String name, XMLString text, boolean isPE)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.internalEntityDecl(name, text, isPE);
        }
    } // internalEntityDecl

    /**
     * externalEntityDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     * @param isPE 
     */
    public void externalEntityDecl(String name, String publicId, String systemId, boolean isPE)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.externalEntityDecl(name, publicId, systemId, isPE );
        }
    } // externalEntityDecl

    /**
     * unparsedEntityDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     * @param notation 
     */
    public void unparsedEntityDecl(String name, String publicId, String systemId, String notation)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.unparsedEntityDecl(name, publicId, systemId, notation );
        }
    } // unparsedEntityDecl

    /**
     * notationDecl
     * 
     * @param name 
     * @param publicId 
     * @param systemId 
     */
    public void notationDecl(String name, String publicId, String systemId)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.notationDecl( name, publicId, systemId );
        }
    } // notationDecl

    /**
     * startConditional
     * 
     * @param type 
     */
    public void startConditional(short type)
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.startConditional( type );
        }
    } // startConditional

    /**
     * endConditional
     */
    public void endConditional()
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.endConditional();
        }
    } // endConditional

    /**
     * endDTD
     */
    public void endDTD()
        throws SAXException {
        if( setDTDHandler != null ){
            setDTDHandler.endDTD();
        }
    } // endDTD

    //
    // XMLDTDContentModelHandler methods
    //

    /**
     * startContentModel
     * 
     * @param elementName 
     * @param type 
     */
    public void startContentModel(String elementName, short type)
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.startContentModel( elementName, type );
        }
    } // startContentModel

    /**
     * mixedElement
     * 
     * @param elementName 
     */
    public void mixedElement(String elementName)
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.mixedElement( elementName );
        }
    } // mixedElement

    /**
     * childrenStartGroup
     */
    public void childrenStartGroup()
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.childrenStartGroup();
        }

    } // childrenStartGroup

    /**
     * childrenElement
     * 
     * @param elementName 
     */
    public void childrenElement(String elementName)
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.childrenElement( elementName );
        }
    } // childrenElement

    /**
     * childrenSeparator
     * 
     * @param separator 
     */
    public void childrenSeparator(short separator)
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.childrenSeparator( separator );
        }
    } // childrenSeparator

    /**
     * childrenOccurrence
     * 
     * @param occurrence 
     */
    public void childrenOccurrence(short occurrence)
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.childrenOccurrence( occurrence );
        }
    } // childrenOccurrence

    /**
     * childrenEndGroup
     */
    public void childrenEndGroup()
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.childrenEndGroup();
        }
    } // childrenEndGroup

    /**
     * endContentModel
     */
    public void endContentModel()
        throws SAXException {
        if( setDTDContentModelHandler != null ){
            setDTDContentModelHandler.endContentModel();
        }
    } // endContentModel

} // class DTDGrammar
