# Makefile for directory ./org/apache/xerces/validators/datatype

TARGETS=\
	AbstractDatatypeValidator.class\
	BinaryDatatypeValidator.class\
	BooleanDatatypeValidator.class\
	DatatypeMessageProvider.class\
	DatatypeValidator.class\
	DatatypeValidatorFactory.class\
	DecimalDatatypeValidator.class\
	DoubleDatatypeValidator.class\
	ENTITYDatatypeValidator.class \
	FloatDatatypeValidator.class\
	IDDatatypeValidator.class \
	IDREFDatatypeValidator.class \
	InvalidDatatypeFacetException.class\
	InvalidDatatypeValueException.class\
	NOTATIONDatatypeValidator.class \
	QNameDatatypeValidator.class\
	StringDatatypeValidator.class\
	URIReferenceDatatypeValidator.class \
	RecurringDurationDatatypeValidator.class\
	TimeDurationDatatypeValidator.class\
	DatatypeValidatorFactoryImpl.class\
	StateMessageDatatype.class\
	XMLException.class 

DIRS = 

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
