# Makefile for directory ./org/apache/xerces/validators/datatype

TARGETS=\
	AbstractDatatypeValidator.class\
	AbstractNumericFacetValidator.class\
	AbstractNumericValidator.class\
	AnyURIDatatypeValidator.class\
	Base64BinaryDatatypeValidator.class\
	BooleanDatatypeValidator.class\
	DatatypeMessageProvider.class\
	DatatypeValidator.class\
	DatatypeValidatorFactory.class\
	DatatypeValidatorFactoryImpl.class\
	DateDatatypeValidator.class\
	DateTimeDatatypeValidator.class\
	DateTimeValidator.class\
	DayDatatypeValidator.class\
	DecimalDatatypeValidator.class\
	DoubleDatatypeValidator.class\
	DurationDatatypeValidator.class\
	ENTITYDatatypeValidator.class \
	FloatDatatypeValidator.class\
	HexBinaryDatatypeValidator.class\
	IDDatatypeValidator.class \
	IDREFDatatypeValidator.class \
	InvalidDatatypeFacetException.class\
	InvalidDatatypeValueException.class\
	ListDatatypeValidator.class \
	MonthDatatypeValidator.class\
	MonthDayDatatypeValidator.class\
	NOTATIONDatatypeValidator.class \
	QNameDatatypeValidator.class\
	SchemaDateTimeException.class\
	StateMessageDatatype.class\
	StringDatatypeValidator.class\
	TimeDatatypeValidator.class\
	UnionDatatypeValidator.class \
	XMLException.class\
	YearDatatypeValidator.class\
	YearMonthDatatypeValidator.class
DIRS = 

TOP = ../../../../../..
include $(TOP)/src/Makefile.incl
